L-Yong99/helloworld

Gemfile.lock, app/models/activity.rb, app/models/itinerary.rb, app/models/place.rb, app/models/review.rb, app/models/user.rb, app/models/users_itinerary.rb, config/routes.rb, db/migrate/20221122093429_create_itineraries.rb, db/migrate/20221122093513_create_places.rb, db/migrate/20221122093528_create_users_itineraries.rb, db/migrate/20221122103843_create_activities.rb, db/migrate/20221122103851_create_reviews.rb, db/schema.rb, test/models/activity_test.rb, test/models/itinerary_test.rb, test/models/place_test.rb, test/models/review_test.rb, test/models/users_itinerary_test.rb
=> added models

app/assets/stylesheets/components/_address_autocomplete.scss, app/assets/stylesheets/utility/_mainUtility.scss, app/controllers/itineraries_controller.rb, app/javascript/controllers/datepicker_controller.js, app/javascript/controllers/index.js, app/views/itineraries/new.html.erb, app/views/layouts/application.html.erb, backup.rb, package.json, yarn.lock
done calendar and search bar logic
=> calendar and searchbar

app/controllers/itineraries_controller.rb, app/javascript/controllers/map_controller.js, app/views/itineraries/plan.html.erb
map working and can retrieve url of geojson
=> map is able to retreive .geojson file

app/controllers/itineraries_controller.rb, app/javascript/controllers/map_controller.js, app/views/itineraries/plan.html.erb
=> complete geojson creation

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_activitybar.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/javascript/controllers/map_controller.js, app/views/itineraries/index.html.erb, app/views/itineraries/new.html.erb, app/views/itineraries/plan.html.erb, app/views/itineraries/summary.html.erb, app/views/layouts/application.html.erb, db/seeds.rb
working copy. In Progress. Made pull request jic later on crash.
=> map click event, detail button, now works with sidebar 

app/assets/stylesheets/components/_activitybar.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_location_filters.scss, app/javascript/controllers/map_controller.js, app/views/itineraries/plan.html.erb
activity sidebar  now extracts all informations
=> side activity bar working with logic

app/assets/stylesheets/pages/_itinerariesPlan.scss, app/javascript/controllers/map_controller.js, app/views/itineraries/plan.html.erb
=> added filter to marker

app/assets/stylesheets/components/_activitybar.scss, app/javascript/controllers/map_controller.js, app/views/itineraries/plan.html.erb
double click zoom disabled
double click open and close activity detail bar 
when activity bar is opened, can click on other activity marker to see correct activity detail
=> Activity details can open with double click and can access other activity details when side bar is active

app/assets/stylesheets/components/_address_autocomplete.scss, app/assets/stylesheets/pages/_itinerariesNew.scss, app/assets/stylesheets/utility/_mainUtility.scss, app/views/itineraries/new.html.erb
=> css done for page new

app/assets/stylesheets/components/_activitybar.scss, app/assets/stylesheets/components/_location_filters.scss, app/assets/stylesheets/pages/_itinerariesPlan.scss, app/views/itineraries/plan.html.erb
However scrollbar design ahving issue
=> part 2 of plan page styling - added left side activity detail css styling 

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_summaryitinerary.scss, app/controllers/itineraries_controller.rb, app/views/itineraries/home.html.erb, app/views/itineraries/summary.html.erb, app/views/shared/_itinerarycard.html.erb
styling for sum itinerary page completed. link for buttons added
=> sumitineraries

app/assets/stylesheets/components/_itinerarycard.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_itinerariesDashboard.scss, app/views/itineraries/dashboard.html.erb, app/views/itineraries/plan.html.erb
dashboard have border to create itineraries and card alignment fixed
=> dashboard can create and itineraries card alignment fixed

app/assets/stylesheets/pages/_itinerariesNew.scss, app/views/itineraries/new.html.erb
=> done new page css

app/assets/stylesheets/pages/_itinerariesNew.scss, app/controllers/itineraries_controller.rb, app/views/itineraries/new.html.erb
=> Done title

app/assets/stylesheets/components/_itinerarycard.scss, app/views/devise/sessions/new.html.erb
=> loginpagefixes

app/assets/stylesheets/components/_activitybar.scss, app/javascript/controllers/map_controller.js, app/views/itineraries/plan.html.erb
Fix scrolling and when click outside of side bar also closes it
=> Fixscrolling

app/controllers/itineraries_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/sortable_controller.js, app/views/itineraries/_sidebar_activity.html.erb, app/views/itineraries/sort.json.jbuilder, config/routes.rb, package.json, yarn.lock
=> added sortable

app/assets/stylesheets/components/_summaryitinerary.scss, app/views/itineraries/summary.html.erb
changes made to summary page, removed creator notes as form will be required to input notes. view gallery button added but not functional. masonry styled image gallery added, logic not in place; pending addition from HX's ongoing trip page.
=> summarypagestatic

app/assets/stylesheets/components/_datessidebar.scss, app/assets/stylesheets/components/_main-card.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/itineraries_controller.rb, app/javascript/controllers/navbar_controller.js, app/views/activities/show.html.erb, app/views/itineraries/plan.html.erb, app/views/layouts/application.html.erb, app/views/shared/_homenavbar.html.erb, app/views/shared/_navbar.html.erb
=> fixed some css bugs

app/assets/stylesheets/components/_summaryitinerary.scss, app/controllers/itineraries_controller.rb, app/views/itineraries/show.html.erb, app/views/shared/_itinerarycard.html.erb
show page up, pending logic to activities
=> showpagelayout

app/assets/stylesheets/components/_summaryitinerary.scss, app/controllers/itineraries_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/summarypage_controller.js, app/views/itineraries/_summary_activities.html.erb, app/views/itineraries/filter.json.jbuilder, app/views/itineraries/summary.html.erb, app/views/shared/_itinerarycard.html.erb, backup.rb, config/routes.rb
done summary page half way, Ajax for activities and photo loading
=> done summary page halfway

app/assets/stylesheets/pages/_itinerariesshow.scss, app/controllers/activities_controller.rb, app/controllers/itineraries_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/map_controller.js, app/javascript/controllers/showmap_controller.js, app/javascript/controllers/sortable_controller.js, app/models/activity.rb, app/models/itinerary.rb, app/views/activities/_sidebar_dayactivities.html.erb, app/views/itineraries/_summary_activities.html.erb, app/views/itineraries/gallery.html.erb, app/views/itineraries/show.html.erb, app/views/itineraries/summary.html.erb, backup.rb
Completed
1. Solve delete of itinerary (bug)
2.  Fixed daily page review sequence on the side bar (bug)
3. Sortable bug fixed ( you can sort all you want now!)
4. Summary/show activities now show places images, not review images
5. Fixed review without uploading image. Can review without image now.
6. Gallery can add multiple images in one shot now
7. Show page now show map with places and country
=> added show map and fixed bugs

app/assets/stylesheets/components/_itinerarycard.scss, app/controllers/itineraries_controller.rb, copy_itinerarycard.html.erb, copyloop_itinerarycard.html.erb
=> Carouseldone

app/views/itineraries/show.html.erb
=> change show page bug

app/assets/stylesheets/pages/_itinerariesshow.scss, app/views/itineraries/show.html.erb
=> show map sticky
